name: alex

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  check-writing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install dependencies
        run: npm ci

      - run: npm run lint

      - run: npm run prettier-check

      - name: Alex writing check
        run: npm run alex
